### ISSUE TITLE
AttributeError in Creator class

### ISSUE THREAD

**Issue by Majsvaffla** [dmkoch/django-jsonfield#189] opened 2017-05-04 13:38 UTC
I updated to Django 1.11 and I get AttributeError from subclassing.py:33. 

In Django 1.11 (django/db/models/options.py:890) the __get__ method of the Creator class is implicitly called. The code in subclassing.py is a copy/paste from Django and seems to be <1.7 and Django's code has updated since then. Simply copying the code from Django 1.7 seems to solve my problems.

**Comment by dmkoch** [comment] 2017-05-04 13:52
Do you have a test case that reproduces the bug?

**Comment by samuelcolvin** [comment] 2017-05-16 11:11
Hi what's happening on this? #190 provides a test case which reproduces it.

If this can't be fixed I think it would be a good idea to remove the erroneous statement in the readme that 1.11 is supported and instead add a note saying support is only partial.

**Comment by dmkoch** [comment] 2017-05-16 11:49
Hi @samuelcolvin sorry I missed #190, I'll see if I can dig into it for a fix.

**Comment by Majsvaffla** [comment] 2017-05-17 12:54
@dmkoch What solved this problem for me was instead of `raise AttributeError('Can only be accessed via an instance.')` in jsonfield/subclassing.py:35 it should simply `return self`. That's what Django did when that file was still around but in 1.11 at least it has been removed.

**Comment by dmkoch** [comment] 2017-05-17 14:47
Thanks @Majsvaffla I'll start looking there.

**Comment by szewczykmira** [comment] 2017-05-29 13:50
Hello @dmkoch, what is current status for this issue?

**Comment by samuelcolvin** [comment] 2017-05-30 11:32
For us, the solution was to move completely to django's own postgres-only json field and stop using django-jsonfield.

**Comment by Majsvaffla** [comment] 2017-05-31 08:03
@samuelcolvin That's actually what we did in the end as well but as I found this solution I thought I'd share it.

**Comment by gitaarik** [comment] 2017-05-31 13:45
Created a pull request for it: https://github.com/dmkoch/django-jsonfield/pull/192

You can use my fork 'till it's merged:

    pip install git+https://github.com/gitaarik/django-jsonfield.git

**Comment by dmkoch** [comment] 2017-06-01 12:36
@Majsvaffla can you confirm that PR #192 by @gitaarik fixes your issue? I already merged the pull request. I will release 2.0.2 after you confirm. Thanks!

**Comment by Majsvaffla** [comment] 2017-06-01 21:12
@dmkoch Yes, #192 solves my problem

**Comment by tkhyn** [comment] 2017-06-01 21:20
@dmkoch same here, that PR fixes that issue

@samuelcolvin and @Majsvaffla as a side note switching to django's own JSONField is not always a good solution as it uses `jsonb` and results in slightly slower write times (django-jsonfield uses `json`). Depends what the use case is.

**Comment by GeyseR** [comment] 2017-06-02 12:59
Hi @dmkoch,
Looks like this issue become actual when using JSON Field in update_or_create/get_or_create method defaults since django v.1.11.2. I guess this introduced in commit https://github.com/django/django/commit/b9abdd92ab21a796943e8047e778eebc671c8c00

Provided PR has fixed issue for me, so waiting for 2.0.2 version

**Comment by szewczykmira** [comment] 2017-06-05 12:05
@dmkoch When can we expect 2.0.2?

**Comment by pembo13** [comment] 2017-06-09 18:33
Just checking in to see the status 2.0.2

**Comment by dmkoch** [comment] 2017-06-18 12:07
I released 2.0.2 today.

**Closed by dmkoch** 2017-06-18 12:07 UTC
